add rstudio bash script
pharmaverse/admiralci pull request #137
Opened 2023-08-04 08:11 UTC by dgrassellyb

2023-08-04 16:52 UTC, galachad requested changes
I think we should keep the script as simple as possible.

2023-08-04 16:52 UTC, galachad commented on .devcontainer/postCreateCommand.sh
> +jq --arg folder "$(pwd)/" '. + { "initial_working_directory": $folder }' .devcontainer/rstudio-prefs.json > ~/.config/rstudio/rstudio-prefs.json
```suggestion
jq --arg folder "$(pwd)/" '. + { "initial_working_directory": $folder }' .devcontainer/rstudio-prefs.json > ~/.config/rstudio/rstudio-prefs.json

```

Add EOF.

2023-08-04 16:52 UTC, galachad commented on .devcontainer/rstudio.sh
> +url_rstudio="https://$url-8787.app.github.dev"
The url is not possible to reach without gitlab auth.

I will propose to keep it simple.

`$BROWSER "https://${CODESPACE_NAME}-8787.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"`

If you would like to check if rstudio is stareted we should query `http://localhost:8787`.

2023-08-04 16:52 UTC, galachad commented on .devcontainer/postCreateCommand.sh
> +cp "$(pwd)/.devcontainer/rstudio.sh" /usr/bin/rstudio
We should also add `sudo` to cp and `chmod +x` to `/usr/bin/rstudio`

```suggestion
sudo cp "$(pwd)/.devcontainer/rstudio.sh" /usr/bin/rstudio
sudo chmod +x /usr/bin/rstudio
```

2023-08-09 11:13 UTC, galachad commented on .devcontainer/rstudio.sh
> +exit 1
```suggestion
#!/bin/bash

$BROWSER "https://${CODESPACE_NAME}-8787.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"

exit 1

```

2023-09-21 10:00 UTC, galachad commented
Hi @dgrassellyb could you take a look on comments?

2023-09-21 11:42 UTC, dgrassellyb commented
> Hi @dgrassellyb could you take a look on comments?

Hi @galachad this one is quite outdated, it's a bit duplicate on what you did for codespaces 
for example you're already doing this command in postAttachCommand `"postAttachCommand": "$BROWSER \"https://${CODESPACE_NAME}-8787.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}/\"",`

I see you suggested to delete the part waiting rstudio server to be ready (rstudio.sh script) - so I guess we can just close this PR

2023-09-21 21:26 UTC, galachad approved these changes
It will be nice to have the `rstudio` command in the console.

I'm merging this PR.

2023-09-21 21:26 UTC, merged